### ISSUE TITLE
Cleaning of query params

### ISSUE THREAD

**Issue by anderscarling** [mrexox/sentry-sanitizer#2]
It would be nice if sentry-sanitizer would be able to filter query params as well, as they obviously can contain sensitive data too.

**Comment by anderscarling** [comment]
Sentry will start suppressing query_params when `config.send_default_pii` is disabled (e.g. default config) which makes this a bit less important - but i still think a more flexible system for suppressing only those params that you want to get rid of could be a nice feature for this gem.

https://github.com/getsentry/sentry-ruby/issues/1140#issuecomment-786983149

**Comment by mrexox** [comment]
Hey! Sorry for a long wait. I have released v0.6.0 with support for query string filtering. See README for configuration!
